### PR TITLE
End stdin on ctrl+d

### PR DESCRIPTION
**Pull request by vendethiel**
Looks like Windows can't generate EOF, which prevents using `coco -s`
- Should it be CTRL+D to be on par with unix ?
- Should it be CTRL+Z because [Wiki said it was the code used back then](http://en.wikipedia.org/wiki/End-of-file)
- maybe another way to track that ? this requires a CR currently.
- do you not want that

### CODE REVIEW

**Comment by satyr** [comment]
> Should it be CTRL+D ...
> Should it be CTRL+Z ...

How about both.

> maybe another way to track that ?

No idea.

> do you not want that

Doesn't hurt I guess. Lemme whip up a cleaner patch.

**Comment by vendethiel** [comment]
Indeed cleaner, but I wanted `3 + 4<ctrl-D>` to work too. (No idea I could've used `it.0` haha...).

**Comment by satyr** [comment]
Uh. So `3 + 4<^D> + 5` should read as `3 + 4` as well?

Seems a lil too much to allow those EOF characters terminate anywhere, since they can validly appear in a JS string.

**Comment by vendethiel** [comment]
No - not anywhere.

``` coffee
if it.0 of [4 26] or it[*-1] of [4 26]
```

While I'm at it, just asking - would you mind a PR for a _real_ website, not just 4/5 coco-related links ? Rather than the additions page.

**Comment by satyr** [comment]
I see, last-position-only makes more sense. Can do that.

Since you have to _enter_ anyway, `code.slice(-3)` would be `'\x04\r\n'` right?

> would you mind a PR for a real website, not just 4/5 coco-related links ? Rather than the additions page.

PR for **index.html**? 'course welcome.

**Comment by vendethiel** [comment]
> right?

yes

> PR for index.html? 'course welcome.

will select a theme and put things in form - got people interested in that too

**Pull request closed without merging**
