### PR TITLE
Add an useful "Try Coco" page

### PR DESCRIPTION
**Pull request by akx**
I wrote a small but (IMHO) handy Try Coco page that uses extras/coco.js.

It's useful for trying out the Coco syntax and also doubles as a REPL of sorts for Coco (you can use CTRL+Enter to execute the generated JavaScript in the browser environment.

### CODE REVIEW

**Comment by michaelficarra** [comment]
... kind of like http://satyr.github.com/cup/?

**Comment by akx** [comment]
@michaelficarra: ... well, didn't know that existed.

**Comment by satyr** [comment]
Cool stuff, but I think it's better as your own, separate project (like http://satyr.github.com/cup/).
Then I can link to it from README etc.

**Comment by scribu** [comment]
@michaelficarra: If only it had a friendlier UI...

**Comment by akx** [comment]
@satyr: Sure. Thanks for the input. :)

**Pull request closed without merging**
